In [1]:
import numpy as np

In [3]:
# populate a list based on conditional values

x = np.array([100,400,-50,-40]) # each element a
y = np.array([10,15,20,25]) # each element b

condition = np.array([True, True, False, False]) # each element cond

z = [a if cond else b for a, cond, b in zip(x, condition, y)]
print(z)

[100, 400, 20, 25]


In [4]:
# using np.where(condition, values for true, values for false)
z2 = np.where(condition, x, y) # simpler than the prev method
print(z2)

[100 400  20  25]


In [5]:
z3 = np.where(x>0, 1, x)
print(z3)

[  1   1 -50 -40]


In [6]:
#standard functions in numpy - sum, sum(0), mean(), std(), var()
print(x.sum())

410


In [8]:
x2 = np.array([[1,2], [3,4]])
print(x2)

[[1 2]
 [3 4]]


In [9]:
print(x2.sum(0)) # gives the sum of columns

[4 6]


In [10]:
print(x.mean())

102.5


In [11]:
print(x.std())

181.71062159378576


In [12]:
print(x.var())

33018.75


In [14]:
# Logical AND OR opertion - any(), all()

condition2 = np.array([True, False, True])

#OR
print(condition2.any())

#AND
print(condition2.all())

True
False


In [16]:
# sort() function 
unsorted = np.array([1,2,10,6,4,3])
print(unsorted)
unsorted.sort()
print(unsorted)

[ 1  2 10  6  4  3]
[ 1  2  3  4  6 10]


In [17]:
# unique
arr2 = np.array(['liquid','liquid','liquid','gas','gas','solid','solid'])
np.unique(arr2) # prints unique elements

array(['gas', 'liquid', 'solid'], dtype='<U6')

In [18]:
# in1d()

print(np.in1d(['solid', 'liquid', 'plasma'], arr2))

[ True  True False]
