In [1]:
import numpy as np

In [2]:
!pip install pandas

You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [3]:
# what is pandas? (nb)
# what is series? (nb)
import pandas as pd
from pandas import Series

In [4]:
# create a simple series variable  
s1 = Series([5,10,15,20])
print(s1)

0     5
1    10
2    15
3    20
dtype: int64


In [5]:
print(s1.values) #prints only the values

[ 5 10 15 20]


In [6]:
print(s1.index) #gives the range of indexes

RangeIndex(start=0, stop=4, step=1)


In [8]:
print(s1.index.values) #gives only the values of indexes

[0 1 2 3]


In [9]:
#create series from numpy
revenue_array = np.array([400, 300, 200, 100])
print(revenue_array)

[400 300 200 100]


In [10]:
revenue_series = Series(revenue_array)
print(revenue_series)

0    400
1    300
2    200
3    100
dtype: int32


In [12]:
# create series wuith custom indexes
revenue = Series(revenue_array, index=['uber', 'ola', 'lyft', 'gojek'])
print(revenue)

uber     400
ola      300
lyft     200
gojek    100
dtype: int32


In [13]:
revenue['ola']

300

In [14]:
revenue['gojek']

100

In [15]:
# filter a series based on conditions
print(revenue[revenue>250])

uber    400
ola     300
dtype: int32


In [16]:
# check whether an element is in a series
print('ola' in revenue)

True


In [17]:
print('grab' in revenue)

False


In [19]:
# to_dict() function
revenue_dict = revenue.to_dict()
print(revenue_dict)

{'uber': 400, 'ola': 300, 'lyft': 200, 'gojek': 100}


In [20]:
# addition of 2 series
print(revenue)
print(revenue+revenue)

uber     400
ola      300
lyft     200
gojek    100
dtype: int32
uber     800
ola      600
lyft     400
gojek    200
dtype: int32


In [22]:
# assign names to a series and its index
revenue.name = 'Comapany - Revenue'
revenue.index.name = "Comapany Name"
print(revenue)

Comapany Name
uber     400
ola      300
lyft     200
gojek    100
Name: Comapany - Revenue, dtype: int32
