In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# why do we need to save arrays to hard drives?

In [5]:
# saving single array
np.save('saved_array', arr) # saved with .npy extension

In [6]:
# loading single array
load_arr1 = np.load('saved_array.npy')
print(load_arr1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# saving multiple array
arr2 = np.arange(25)
arr3 = np.arange(5)

np.savez('saved_archieve.npz', x = arr2, y = arr3) # saved as a zip file

In [9]:
# loading multiple arrray
load_npz = np.load('saved_archieve.npz')
print(load_npz['x']) # arr2
print(load_npz['y']) # arr3

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[0 1 2 3 4]


In [11]:
# it is not possible to open .npy or .npz file to open in computer
# saving array to text file

np.savetxt('myarray.txt', arr2, delimiter=',')

In [12]:
# loading array from text file

load_file = np.loadtxt('myarray.txt', delimiter=',')
print(load_file)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]


In [ ]:
# what is a delimiter?
# symbol which separates the elements of the array (',','-', etc)