In [1]:
import numpy as np

In [4]:
arr = np.arange(100, 160, 2)
print(arr)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [5]:
# intro to indexes
print("First element")
print(arr[0])
print("Third element")
print(arr[2])
print("Sixth element")
print(arr[5])

First element
100
Third element
104
Sixth element
110


In [6]:
# slicing of array indexes arr[start: stop: step]
print(arr[0:5:1]) # 5 is excluded


[100 102 104 106 108]


In [7]:
# updating array using slice
arr[0:5] = 0
print(arr)

[  0   0   0   0   0 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [11]:
# Interesting point about slicing - memory allocation - view vs copy
arr2 = arr[4: 10]
arr2[:] = 1 # sets all values of arr to 1
print(arr2)

[1 1 1 1 1 1]


In [12]:
print(arr)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [13]:
# copy() function -> creating new numpy memory for array

arr3 = arr.copy()
print(arr3)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [14]:
arr3[:] = 0
print(arr3)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [15]:
print(arr)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]
