In [1]:
import numpy as np

In [2]:
# creating 1D Numpy Array
mylist1 = [101, 102, 103]
myArray = np.array(mylist1)
print(myArray)

[101 102 103]


In [4]:
# creating 2D Numpy Array
mylist2 = [201, 202, 203]
myArray2D = np.array([mylist1, mylist2])
print(myArray2D)

[[101 102 103]
 [201 202 203]]


In [6]:
# Finding dimensions of array - shape
print("myArray Dimension")
print(myArray.shape)
print("myArray2D Dimension")
print(myArray2D.shape)

myArray Dimension
(3,)
myArray2D Dimension
(2, 3)


In [7]:
# Finding Datatype of Array - dtype
print("myArray Datatype")
print(myArray.dtype)
print("myArray2D Datatpe")
print(myArray2D.dtype)

myArray Datatype
int32
myArray2D Datatpe
int32


In [9]:
# Array creation and initialisation function - zeros
zero_array = np.zeros(5)
print(zero_array)

zero_array2D = np.zeros([5,5])
print(zero_array2D)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
# Array creation and initialisation function - ones
ones_array = np.ones(5)
print(ones_array)

ones_array2D = np.ones([5,5])
print(ones_array2D)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
# Array creation and initialisation function - empty
emptyArray = np.empty(5)
print(emptyArray) #all values of emptyArray is '1' because it is the last stored value

emptyArray2D = np.empty([5, 5])
print(emptyArray2D)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
# Array creation and initialisation function - eye
identityArray = np.eye(5) #creates identity matrix - all diagonal elements is '1'
print(identityArray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
# Array creation and initialisation function arange
AP_array = np.arange(0, 50, 2) #start value, end value (50 not included), difference
print(AP_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
