In [1]:
import numpy as np

In [3]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Accessing Rows
print(arr2d[0])
print(arr2d[2])

[1 2 3]
[7 8 9]


In [6]:
# Accessing elements of Array
print(arr2d[0][0])

1


In [8]:
print(arr2d[1][2])

6


In [9]:
# slicing in 2d arrays
slice1 = arr2d[0:1, 0:2]
print(slice1)

[[1 2]]


In [10]:
slice2 = arr2d[0:2, 0:3]
print(slice2)

[[1 2 3]
 [4 5 6]]


In [11]:
slice3 = arr2d[:2, :3]
print(slice3)

[[1 2 3]
 [4 5 6]]


In [13]:
slice4 = arr2d[1:, 2:]
print(slice4)

[[6]
 [9]]


In [17]:
# using loops to change index
arr_len = arr2d.shape # (3,3)
print(arr_len) 

nrows = arr_len[0]
print(nrows)

(3, 3)
3


In [18]:
for i in range(nrows):
    arr2d[i][0] = i # changing all first column elements
print(arr2d)

[[0 2 3]
 [1 5 6]
 [2 8 9]]


In [19]:
# accessing rows using list of index values 
print(arr2d[[0,1]]) #will print 1st row first and 2nd row second

[[0 2 3]
 [1 5 6]]


In [21]:
print(arr2d[[1,0]]) #will print 2nd row first and 1st row second

[[1 5 6]
 [0 2 3]]
