In [1]:
import numpy as np

In [2]:
# arange() function
A = np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
B = np.arange(5, 10)
print(B)

[5 6 7 8 9]


In [4]:
C = np.arange(5, 10, 2)
print(C)

[5 7 9]


In [5]:
# sqrt() function
D = np.sqrt(A)
print(D)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


In [6]:
# exp() function
E = np.exp(A) # e=2.718, basically exp() is e^x
print(E)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06]


In [11]:
# random() function
F = np.random.randn(5) # 1D array
print(F)
F = np.random.randn(5,5) # 2D array
print(F)

[ 0.66221148  0.90761081  0.03009621 -1.22629325 -0.22130859]
[[-0.19941114  0.08545567  0.09992663 -0.12908329 -0.75837153]
 [-1.38908449  1.53090687 -0.32712754  0.79550534 -0.40319633]
 [ 1.22150161  0.17004612 -1.30513537  2.27365651  0.04628576]
 [-0.22262846 -0.67431665  0.62780323 -0.42512832  2.22859207]
 [-0.18197626 -1.42097056  0.3938163   0.20032761  1.17938807]]


In [13]:
# add() function
print(A)
print(D)

G = np.add(A,D)
print(G)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]
[ 0.          2.          3.41421356  4.73205081  6.          7.23606798
  8.44948974  9.64575131 10.82842712 12.         13.16227766 14.31662479
 15.46410162 16.60555128 17.74165739]


In [15]:
# maximum() function
A = np.array([1,5,7,10])
B = np.array([0,6,8,9])
 
H = np.maximum(A,B) # prints the max out of the 2 arrays
print(H)

[ 1  6  8 10]


In [ ]:
# Numpy additional documentations - numpy.org; docs.scipy.org