In [1]:
import numpy as np

In [2]:
# What is scalar operations

In [3]:
# Scalar Array Multiplication - using * operator

arr1 = np.array([[1,2,3], [4, 5, 6]])
print(arr1)


[[1 2 3]
 [4 5 6]]


In [4]:
arr2 = arr1 * arr1
print(arr2)

[[ 1  4  9]
 [16 25 36]]


In [6]:
# exponential multiplication using ** operator
arr3 = arr1 ** 3
print(arr3)

[[  1   8  27]
 [ 64 125 216]]


In [7]:
#Scalar subtraction of array elements
arr4 = arr3 - arr1
print(arr4)

[[  0   6  24]
 [ 60 120 210]]


In [10]:
# Scalar Division of Array Elements
arr5 = 1 / arr1
print(arr5)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
